### ISSUE TITLE
Error: Input required and not supplied: git_commit_sha 

### ISSUE THREAD

**Issue by mzaatar** [pkgdeps/git-tag-action#8]
The documentation said that `git_commit_sha` is optional but I got an error when not supplying it.

My GitHub workflow is as follows:

```
name: Create git tag

on:
  workflow_call:
    inputs:
      tag:
        description: "Git tag"
        required: true
        type: string

jobs:
  push-git-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # Push tag to GitHub if the version's tag is not tagged
      - name: push-version-to-git-tag
        uses: pkgdeps/git-tag-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          version: ${{ inputs.tag }}
```

Results:
```
Run pkgdeps/git-tag-action@v2
  with:
    github_token: ***
    github_repo: abc/xyz
    version: v.10-beta
Error: Input required and not supplied: git_commit_sha
```
